### ISSUE TITLE
Error: Cannot resolve module 'font-awesome/less/extras.less'

### ISSUE THREAD

**Issue by rubyconvict** [protolab/webpack-flightjs-demo#1]
```
webpack-flightjs-demo (master=)$ node_modules/webpack-dev-server/bin/webpack-dev-server.js -d --optimize-dedupe --progress --colors --display-error-details --hot
 70% 1/1 build moduleshttp://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from /Users/me/projects/webpack-flightjs-demo
Hash: f8fc2d756f8f91ee770d
Version: webpack 1.5.3
Time: 1737ms
                                    Asset    Size  Chunks             Chunk Names
     df7b648ce5356ea1ebce435b3459fd60.ttf  126072          [emitted]
     549ec3575943fef98f76b46924ff5efa.ttf  132440          [emitted]
     e31fcf1885e371e19f5786c2bdfeae1b.ttf  127744          [emitted]
     b03c5eb442028f11bc008e89f46861f6.ttf  134556          [emitted]
    f8fc2d756f8f91ee770d.vendor.bundle.js  369630       0  [emitted]  vendor
           f8fc2d756f8f91ee770d.bundle.js    6694       1  [emitted]  app
f8fc2d756f8f91ee770d.vendor.bundle.js.map  448449       0  [emitted]  vendor
       f8fc2d756f8f91ee770d.bundle.js.map    7856       1  [emitted]  app
                               index.html     454          [emitted]
chunk    {0} f8fc2d756f8f91ee770d.vendor.bundle.js, f8fc2d756f8f91ee770d.vendor.bundle.js.map (vendor) 326781 [rendered]
    [0] multi vendor 76 {0} [built]
    [1] ./bower_components/flight/index.js 546 {0} [built]
    [2] ./~/font-awesome-webpack/index.js 74 {0} [built]
    [3] ./bower_components/jquery/dist/jquery.js 247387 {0} [built]
    [4] ./~/hogan.js/lib/hogan.js 810 {0} [built]
    [5] ./bower_components/flight/lib/advice.js 1833 {0} [built]
    [6] ./bower_components/flight/lib/component.js 4206 {0} [built]
    [7] ./bower_components/flight/lib/compose.js 865 {0} [built]
    [8] ./bower_components/flight/lib/debug.js 5298 {0} [built]
    [9] ./bower_components/flight/lib/logger.js 3059 {0} [built]
   [10] ./bower_components/flight/lib/registry.js 6065 {0} [built]
   [11] ./bower_components/flight/lib/utils.js 8551 {0} [built]
   [13] ./bower_components/normalize-css/normalize.css 1561 {0} [built]
   [14] ./~/css-loader!./~/autoprefixer-loader?browsers=last 2 version!./bower_components/normalize-css/normalize.css 8303 {0} [built]
   [15] ./~/hogan.js/lib/compiler.js 12052 {0} [built]
   [16] ./~/hogan.js/lib/template.js 9269 {0} [built]
   [17] ./~/style-loader/addStyles.js 5507 {0} [built]
   [20] ./~/style-loader!./~/font-awesome-webpack/~/css-loader!./~/font-awesome-webpack/~/less-loader!./~/font-awesome-webpack/font-awesome-styles.loader.js!./~/font-awesome-webpack/font-awesome.config.js 2035 {0} [built] [1 error]
   [22] ./bower_components/flight/lib/base.js 8932 {0} [built]
   [23] ./~/css-loader/cssToString.js 352 {0} [built]
chunk    {1} f8fc2d756f8f91ee770d.bundle.js, f8fc2d756f8f91ee770d.bundle.js.map (app) 4925 {0} [rendered]
    [0] ./app/scripts/app.js 174 {1} [built]
   [12] ./app/scripts/component/ui/click-counter.js 991 {1} [built]
   [18] ./app/styles/main.scss 1792 {1} [built]
   [19] ./~/css-loader!./~/autoprefixer-loader?browsers=last 2 version!./~/sass-loader?outputStyle=expanded!./app/styles/main.scss 1135 {1} [built]
   [24] ./app/templates/default-click-counter.hgn 509 {1} [built]
   [37] ./app/fonts/Roboto-Regular.ttf 81 {1} [built]
   [38] ./app/fonts/Roboto-Italic.ttf 81 {1} [built]
   [39] ./app/fonts/Roboto-Bold.ttf 81 {1} [built]
   [40] ./app/fonts/Roboto-BoldItalic.ttf 81 {1} [built]

ERROR in ./~/font-awesome-webpack/~/css-loader!./~/font-awesome-webpack/~/less-loader!./~/font-awesome-webpack/font-awesome-styles.loader.js!./~/font-awesome-webpack/font-awesome.config.js
Module build failed: Error: Cannot resolve module 'font-awesome/less/extras.less' in /Users/me/projects/webpack-flightjs-demo/node_modules/font-awesome-webpack
    at innerCallback (/Users/me/projects/webpack-flightjs-demo/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:91:16)
    at loggingCallbackWrapper (/Users/me/projects/webpack-flightjs-demo/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/me/projects/webpack-flightjs-demo/node_modules/webpack/node_modules/tapable/lib/Tapable.js:138:6
    at /Users/me/projects/webpack-flightjs-demo/node_modules/webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
    at /Users/me/projects/webpack-flightjs-demo/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /Users/me/projects/webpack-flightjs-demo/node_modules/webpack/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
    at loggingCallbackWrapper (/Users/me/projects/webpack-flightjs-demo/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/me/projects/webpack-flightjs-demo/node_modules/webpack/node_modules/tapable/lib/Tapable.js:138:6
    at /Users/me/projects/webpack-flightjs-demo/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:122:33
    at /Users/me/projects/webpack-flightjs-demo/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
 @ ./~/style-loader!./~/font-awesome-webpack/~/css-loader!./~/font-awesome-webpack/~/less-loader!./~/font-awesome-webpack/font-awesome-styles.loader.js!./~/font-awesome-webpack/font-awesome.config.js 4:14-466 12:19-471
webpack: bundle is now VALID.
```

**Comment by protolab** [comment]
Thank you for your feedback.

FA 4.3.0 doesn't have 'extras.less' anymore. The 'font-awesome-webpack' hasn't been updated for several months and works only with FA 4.2.0.
